name: docs_seekrflow
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python=3.12
  - pip
  - cython
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  
    # Pip-only installs
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme

